name: sv-test-env
channels:
  - LiteX-Hub
  - pkgw-forge
  - conda-forge
dependencies:
#  - LiteX-Hub::iverilog
#  - LiteX-Hub::moore
#  - LiteX-Hub::odin_ii
#  - LiteX-Hub::slang
#  - LiteX-Hub::surelog
#  - LiteX-Hub::sv-parser
#  - LiteX-Hub::tree-sitter-verilog
#  - LiteX-Hub::uhdm-integration-verilator
#  - LiteX-Hub::uhdm-integration-yosys
#  - LiteX-Hub::verible
#  - LiteX-Hub::verilator
#  - LiteX-Hub::yosys
#  - LiteX-Hub::antmicro-yosys-complete
#  - LiteX-Hub::zachjs-sv2v
  - ccache
  - python=3.8
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
